# Generated by Django 3.0.3 on 2020-03-17 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('upload_date_time', models.DateTimeField(auto_now=True)),
                ('file_type', models.CharField(choices=[('FA', 'FA Risk'), ('TC', 'TCU Defaulter'), ('IR', 'IRMS'), ('PC', 'Postal Code'), ('RB', 'Rental Block')], default='FA', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generated', models.DateField()),
                ('patient_id', models.CharField(max_length=20)),
                ('house_block', models.CharField(max_length=10)),
                ('house_floor', models.IntegerField(null=True)),
                ('house_unit', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField(null=True)),
                ('region', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tcu_Defaulter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generated', models.DateField()),
                ('patient_id', models.CharField(max_length=20)),
                ('postal_code', models.IntegerField(null=True)),
                ('street', models.CharField(max_length=100)),
                ('house_block', models.CharField(max_length=10)),
                ('house_floor', models.IntegerField(null=True)),
                ('house_unit', models.CharField(max_length=100)),
                ('visit_type', models.CharField(max_length=10)),
                ('first_visit_model', models.FloatField(null=True)),
                ('repeat_visit_model', models.FloatField(null=True)),
                ('overall_model', models.FloatField(null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ULM.File')),
            ],
        ),
        migrations.CreateModel(
            name='Rental_Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_block', models.CharField(max_length=10)),
                ('postal_code', models.IntegerField(null=True)),
                ('street', models.CharField(max_length=100)),
                ('one_room_flat', models.BooleanField(null=True)),
                ('two_room_flat', models.BooleanField(null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ULM.File')),
            ],
        ),
        migrations.CreateModel(
            name='Postal_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('low_bound', models.IntegerField(null=True)),
                ('high_bound', models.IntegerField(null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ULM.File')),
            ],
        ),
        migrations.CreateModel(
            name='Irms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20)),
                ('postal_code', models.IntegerField(null=True)),
                ('house_block', models.CharField(max_length=10)),
                ('house_floor', models.IntegerField(null=True)),
                ('house_unit', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('ref_submission_date', models.DateField()),
                ('latest_outcome', models.CharField(max_length=100)),
                ('application_status', models.CharField(max_length=100)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ULM.File')),
            ],
        ),
        migrations.CreateModel(
            name='Fa_Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generated', models.DateField()),
                ('patient_id', models.CharField(max_length=20)),
                ('house_block', models.CharField(max_length=10)),
                ('house_floor', models.IntegerField(null=True)),
                ('house_unit', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField(null=True)),
                ('fa_risk', models.CharField(max_length=100)),
                ('fa', models.CharField(max_length=100)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ULM.File')),
            ],
        ),
    ]
