# Generated by Django 3.0.3 on 2020-03-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fa_risk',
            name='patient_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fa_risk',
            name='patient_nric',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='irms',
            name='patient_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='irms',
            name='patient_nric',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient_info',
            name='patient_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient_info',
            name='patient_nric',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tcu_defaulter',
            name='patient_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tcu_defaulter',
            name='patient_nric',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
